[package]
name = "hn"
version = "0.1.0"
authors = ["Trevor Bentley <mrmekon@gmail.com>"]

[dependencies]
hyper = "0.11.1"
tokio-core = "0.1.9"
futures = "0.1.14"
hyper-tls = "0.1.2"
serde = "1.0.10"
serde_json = "1.0.2"
serde_derive = "1.0.10"
